### ISSUE TITLE
Java version support policy

### ISSUE THREAD

**Issue by jorsol** [codehaus-plexus/plexus-components#27]
This is more a general question than an issue, many plexus components started to require Java 8 yet Maven 3.3+ still requires Java 7, so, since Maven heavily uses plexus components there is a need to be compatible with Maven or the new versions of the components only tracks future Maven versions (that requires Java 8)?

What is the policy to bump required Java versions in plexus?
Is there a compatibility list that tracks what Java version is supported?

**Comment by michael-o** [comment]
A very decent question.

**Comment by slachiewicz** [comment]
i would say that more and more projects just discards Java 8

**Comment by slachiewicz** [comment]
Now Java 8 is base requirements for all components - same as we migrate other Maven projects
