### ISSUE TITLE
drop this repo and use plexus-pom directly

### ISSUE THREAD

**Issue by slachiewicz** [codehaus-plexus/plexus-components#58]
- [x] https://github.com/codehaus-plexus/plexus-resources
- [x] https://github.com/codehaus-plexus/plexus-interactivity
- [x] https://github.com/codehaus-plexus/plexus-velocity
- [x] https://github.com/codehaus-plexus/plexus-i18n
- [x] https://github.com/codehaus-plexus/plexus-cli
- [x] https://github.com/codehaus-plexus/plexus-digest

**Comment by slawekjaranowski** [comment]
👍

**Comment by slachiewicz** [comment]
All migrated
